export const SET_LOGIN_STATE = "SET_LOGIN_STATE";
export const SET_INITIAL_STATE = "SET_INITIAL_STATE";
export const SET_REGISTER_STATE = "SET_REGISTER_STATE";
export const SET_LOGOUT_STATE = "SET_LOGOUT_STATE"; 
export const SET_LOGIN_FAIL_STATE = "SET_LOGIN_FAIL_STATE"; 
export const SET_LOGIN_CLEAR_STATE = "SET_LOGIN_CLEAR_STATE"; 