export const SET_LOGIN_STATE = "SET_LOGIN_STATE";
export const SET_INITIAL_STATE = "SET_INITIAL_STATE";
export const SET_REGISTER_STATE = "SET_REGISTER_STATE";
export const SET_LOGOUT_STATE = "SET_LOGOUT_STATE"; 
export const SET_LOGIN_FAIL_STATE = "SET_LOGIN_FAIL_STATE"; 
export const SET_LOGIN_CLEAR_STATE = "SET_LOGIN_CLEAR_STATE"; 

export const SET_USER_STATE = "SET_USER_STATE";
export const SET_USER_SUCCESS = "SET_USER_SUCCESS";
export const SET_USER_FAIL = "SET_USER_FAIL";

export const SET_SESSION_STATE = "SET_SESSION_STATE";
export const SET_SESSION_SUCCESS = "SET_SESSION_SUCCESS";
export const SET_SESSION_FAIL = "SET_SESSION_FAIL";

export const SET_CLASS_STATE = "SET_CLASS_STATE";
export const SET_CLASS_SUCCESS = "SET_CLASS_SUCCESS";
export const SET_CLASS_FAIL = "SET_CLASS_FAIL";